require_relative  "./conversion/type"
require_relative  "./conversion/numbers"
require_relative  "./conversion/calculator"
require_relative  "./conversion/parse"
require_relative  "./conversion/roman/converter"
