require_relative  "./conversion/type"
require_relative  "./conversion/numbers"
require_relative  "./conversion/calculator"
require_relative  "./conversion/parse"
require_relative  "./conversion/converters/base"
require_relative  "./conversion/converters/roman"
require_relative  "./conversion/converters/alien"
